name: Test front

on:
  pull_request:
  push:
    branches:
      - master
    paths:
      - 'server/**'
jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.15.0]
    steps:

      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Start backend
        working-directory: server
        run: |
          npm install
          npm test
          
      - name: Login to docker hub
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build :latest
        working-directory: server/
        run: docker build -t newtest001/backend:latest .

      - name: Push to docker hub :latest
        uses: actions-hub/docker@master
        with:
          args: push newtest001/backend:latest
