name: Test front

on:
  pull_request:
  push:
    branches:
      - master
    paths:
      - 'client/**'
jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.15.0]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Start frontend test
        working-directory: client/
        run: |
          yarn install
          yarn test
          
      - name: Login to docker hub
        uses: actions-hub/docker/login@myrepo
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build :latest
        working-directory: client/
        run: docker build -t frontend:latest .

      - name: Push to docker hub :latest
        uses: actions-hub/docker@myrepo
        with:
          args: push frontend:latest
        
        
        
