name: Test front

on:
  pull_request:
  push:
    branches:
      - master
    paths:
      - 'client/**'
jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.15.0]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - name: Start
        working-directory: client/
        run: |
          yarn install
          yarn test
